title: Source Agnostic Reconstruction of Neurons challenge
description: Challenge for measuring the generalization capabilities of present Neural Network architectures
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
